steps:
- name: python
  entrypoint: bash
  args: ['-c', 'pip install -U dvc dvc[gs]; dvc pull;']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mlops-lauritsf/testing', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mlops-lauritsf/testing']
